In [1]:
import pandas as pd
df=pd.DataFrame([800,1000,1200,1500,2000])
df

      0
0   800
1  1000
2  1200
3  1500
4  2000

In [2]:
x=df.iloc[:,[0]]
x

      0
0   800
1  1000
2  1200
3  1500
4  2000

In [3]:
#normaization
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_scaler=scaler.fit_transform(x)
x_scaler

array([[0.        ],
       [0.16666667],
       [0.33333333],
       [0.58333333],
       [1.        ]])

In [4]:
pre=scaler.transform([[1300]])
pre

array([[0.41666667]])

In [5]:
#StandardScaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
x_scaled

array([[-1.19182824],
       [-0.71509694],
       [-0.23836565],
       [ 0.47673129],
       [ 1.66855953]])

In [6]:
scaler.mean_

array([1300.])

In [7]:
scaler.scale_

array([419.52353927])

In [9]:
scaler.transform([[1300]])

array([[0.]])